const charList = [
    //character, searches, picture
    ["Albedo", "5star", "images/characters/albedo.webp", "geo"],
    ["Aloy", "5star", "images/characters/aloy.webp", "cryo"],
    ["Amber", "4star", "images/characters/amber.webp", "pyro"],
    ["Arataki Itto", "5star", "images/characters/itto.webp", "geo"],
    ["Barbara", "4star", "images/characters/barbara.webp", "hydro"],
    ["Beidou", "4star", "images/characters/beidou.webp", "electro"],
    ["Bennett", "4star", "images/characters/bennett.webp", "pyro"],
    ["Chongyun", "4star", "images/characters/chongyun.webp", "cryo"],
    ["Diluc", "5star", "images/characters/diluc.webp", "pyro"],
    ["Diona", "4star", "images/characters/diona.webp", "cryo"],
    ["Eula", "5star", "images/characters/eula.webp", "cryo"],
    ["Fischl", "4star", "images/characters/fischl.webp", "electro"],
    ["Ganyu", "5star", "images/characters/ganyu.webp", "cryo"],
    ["Gorou", "4star", "images/characters/gorou.webp", "geo"],
    ["Jean", "5star", "images/characters/jean.webp", "anemo"],
    ["Kazuha", "5star", "images/characters/kazuha.webp", "anemo"],
    ["Kaeya", "4star", "images/characters/kaeya.webp", "cryo"],
    ["Ayaka", "5star", "images/characters/ayaka.webp", "cryo"],
    ["Keqing", "5star", "images/characters/keqing.webp", "electro"],
    ["Kujou Sara", "4star", "images/characters/sara.webp", "electro"],
    ["Lisa", "4star", "images/characters/lisa.webp", "electro"],
    ["Mona", "5star", "images/characters/mona.webp", "hydro"],
    ["Ningguang", "4star", "images/characters/ningguang.webp", "geo"],
    ["Noelle", "4star", "images/characters/noelle.webp", "geo"],
    ["Raiden Shogun", "5star", "images/characters/raiden.webp", "electro"],
    ["Rosaria", "4star", "images/characters/rosaria.webp", "cryo"],
    ["Sayu", "4star", "images/characters/sayu.webp", "anemo"],
    ["Sucrose", "4star", "images/characters/sucrose.webp", "anemo"],
    ["Traveler", "5star", "images/characters/traveler.webp", "KEKW"],
    ["Venti", "5star", "images/characters/venti.webp", "anemo"]
    ["Xiangling", "4star", "images/characters/xiangling.webp", "pyro"],
    ["Xingqiu", "4star", "images/characters/xingqiu.webp", "hydro"],
    ["Xinyan", "4star", "images/characters/xinyan.webp", "pyro"],
    ["Yanfei", "4star", "images/characters/yanfei.webp", "pyro"],
    ["Yae Miko", "5star", "images/characters/yae.webp", "electro"],
    ["Yun Jin", "4star", "images/characters/yunjin.webp", "geo"],
    ["Zhongli", "5star", "images/characters/zhongli.webp", "geo"],
];